-- MySQL Script generated by MySQL Workbench
-- Wed Feb 20 21:23:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema torneo-municipal-111mil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema torneo-municipal-111mil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `torneo-municipal-111mil` DEFAULT CHARACTER SET utf8 ;
USE `torneo-municipal-111mil` ;

-- -----------------------------------------------------
-- Table `torneo-municipal-111mil`.`aspirante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo-municipal-111mil`.`aspirante` (
  `idAspirante` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `apellido` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `direccion` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `fecha-nacimiento` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `sexo` VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `dni` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `escuelaID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idAspirante`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `torneo-municipal-111mil`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo-municipal-111mil`.`categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `torneo-municipal-111mil`.`inscripcion-aspirante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo-municipal-111mil`.`inscripcion-aspirante` (
  `idInsAsp` INT(11) NOT NULL AUTO_INCREMENT,
  `aspirante` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `categoria` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idInsAsp`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `torneo-municipal-111mil`.`detalle_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo-municipal-111mil`.`detalle_disciplina` (
  `idInsAsp` INT(11) NOT NULL,
  `idDetDis` INT(11) NOT NULL,
  `disciplina` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idInsAsp`, `idDetDis`),
  CONSTRAINT `FK_detalle_disciplina_inscripcion-aspirante_idInsAsp`
    FOREIGN KEY (`idInsAsp`)
    REFERENCES `torneo-municipal-111mil`.`inscripcion-aspirante` (`idInsAsp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `torneo-municipal-111mil`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo-municipal-111mil`.`disciplina` (
  `idDisciplina` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreDisciplina` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `torneo-municipal-111mil`.`escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torneo-municipal-111mil`.`escuela` (
  `idEscuela` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreEscuela` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`idEscuela`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
